import json
import re

print("Loading raw extracted files...")
cheat_sheet = json.load(open('country_cheat_sheet.json', encoding='utf-8'))
modes_json = json.load(open('01_modes.json', encoding='utf-8'))
fund_json = json.load(open('02_fundamentals.json', encoding='utf-8'))
highways_json = json.load(open('03_highway_numbering.json', encoding='utf-8'))
general_json = json.load(open('04_general_clues.json', encoding='utf-8'))
meta_json = json.load(open('05_meta.json', encoding='utf-8'))
plates_json = json.load(open('06_license_plates.json', encoding='utf-8'))
languages_json = json.load(open('07_languages.json', encoding='utf-8'))

# Country Flag and TLD mapping
FLAG_TLD_MAP = {
    "USA": ("🇺🇸", ".us"),
    "Canada": ("🇨🇦", ".ca"),
    "Puerto Rico": ("🇵🇷", ".pr"),
    "The Dominican Republic": ("🇩🇴", ".do"),
    "Costa Rica": ("🇨🇷", ".cr"),
    "Mexico": ("🇲🇽", ".mx"),
    "Guatemala": ("🇬🇹", ".gt"),
    "US Virgin Islands": ("🇻🇮", ".vi"),
    "Bermuda": ("🇧🇲", ".bm"),
    "Panama": ("🇵🇦", ".pa"),
    "Ireland": ("🇮🇪", ".ie"),
    "The U.K.": ("🇬🇧", ".uk"),
    "The Isle of Man": ("🇮🇲", ".im"),
    "Jersey": ("🇯🇪", ".je"),
    "Portugal": ("🇵🇹", ".pt"),
    "Spain": ("🇪🇸", ".es"),
    "The Canary Islands": ("🇮🇨", ".es"),
    "Andorra": ("🇦🇩", ".ad"),
    "Gibraltar": ("🇬🇮", ".gi"),
    "France": ("🇫🇷", ".fr"),
    "Belgium": ("🇧🇪", ".be"),
    "The Netherlands": ("🇳🇱", ".nl"),
    "Luxembourg": ("🇱🇺", ".lu"),
    "Italy": ("🇮🇹", ".it"),
    "San Marino": ("🇸🇲", ".sm"),
    "Norway": ("🇳🇴", ".no"),
    "Svalbard": ("🇸🇯", ".sj"),
    "Sweden": ("🇸🇪", ".se"),
    "Finland": ("🇫🇮", ".fi"),
    "Denmark": ("🇩🇰", ".dk"),
    "The Faroe Islands": ("🇫🇴", ".fo"),
    "Iceland": ("🇮🇸", ".is"),
    "Greenland": ("🇬🇱", ".gl"),
    "Germany": ("🇩🇪", ".de"),
    "Austria": ("🇦🇹", ".at"),
    "Switzerland": ("🇨🇭", ".ch"),
    "Liechtenstein": ("🇱🇮", ".li"),
    "Poland": ("🇵🇱", ".pl"),
    "Lithuania": ("🇱🇹", ".lt"),
    "Latvia": ("🇱🇻", ".lv"),
    "Estonia": ("🇪🇪", ".ee"),
    "Czechia (The Czech Republic)": ("🇨🇿", ".cz"),
    "Slovakia": ("🇸🇰", ".sk"),
    "Slovenia": ("🇸🇮", ".si"),
    "Hungary": ("🇭🇺", ".hu"),
    "Croatia": ("🇭🇷", ".hr"),
    "Bosnia and Herzegovina": ("🇧🇦", ".ba"),
    "Albania": ("🇦🇱", ".al"),
    "Greece": ("🇬🇷", ".gr"),
    "Cyprus": ("🇨🇾", ".cy"),
    "Romania": ("🇷🇴", ".ro"),
    "Montenegro": ("🇲🇪", ".me"),
    "Serbia": ("🇷🇸", ".rs"),
    "North Macedonia": ("🇲🇰", ".mk"),
    "Bulgaria": ("🇧🇬", ".bg"),
    "Ukraine": ("🇺🇦", ".ua"),
    "Russia": ("🇷🇺", ".ru"),
    "The Russian Landscape": ("🇷🇺", ".ru"),
    "Malta": ("🇲🇹", ".mt"),
    "Australia": ("🇦🇺", ".au"),
    "New Zealand": ("🇳🇿", ".nz"),
    "American Samoa": ("🇦🇸", ".as"),
    "Northern Mariana Islands": ("🇲🇵", ".mp"),
    "Guam": ("🇬🇺", ".gu"),
    "Midway Atoll": ("🇺🇸", ".us"),
    "Christmas Island": ("🇨🇽", ".cx"),
    "South Africa": ("🇿🇦", ".za"),
    "Botswana": ("🇧🇼", ".bw"),
    "Eswatini": ("🇸🇿", ".sz"),
    "Lesotho": ("🇱🇸", ".ls"),
    "Namibia": ("🇳🇦", ".na"),
    "Uganda": ("🇺🇬", ".ug"),
    "Kenya": ("🇰🇪", ".ke"),
    "Rwanda": ("🇷🇼", ".rw"),
    "Ghana": ("🇬🇭", ".gh"),
    "Nigeria": ("🇳🇬", ".ng"),
    "Senegal": ("🇸🇳", ".sn"),
    "Tunisia": ("🇹🇳", ".tn"),
    "Reunion": ("🇷🇪", ".re"),
    "Madagascar": ("🇲🇬", ".mg"),
    "Sao Tome and Principe": ("🇸🇹", ".st"),
    "Bhutan": ("🇧🇹", ".bt"),
    "Hong Kong": ("🇭🇰", ".hk"),
    "Macau": ("🇲🇴", ".mo"),
    "Japan": ("🇯🇵", ".jp"),
    "Cambodia": ("🇰🇭", ".kh"),
    "Thailand": ("🇹🇭", ".th"),
    "Taiwan": ("🇹🇼", ".tw"),
    "South Korea": ("🇰🇷", ".kr"),
    "The United Arab Emirates": ("🇦🇪", ".ae"),
    "Jordan": ("🇯🇴", ".jo"),
    "Qatar": ("🇶🇦", ".qa"),
    "Oman": ("🇴🇲", ".om"),
    "Israel": ("🇮🇱", ".il"),
    "Palestine": ("🇵🇸", ".ps"),
    "Lebanon": ("🇱🇧", ".lb"),
    "Kyrgyzstan": ("🇰🇬", ".kg"),
    "Mongolia": ("🇲🇳", ".mn"),
    "Kazakhstan": ("🇰🇿", ".kz"),
    "Indonesia": ("🇮🇩", ".id"),
    "Malaysia": ("🇲🇾", ".my"),
    "Vietnam": ("🇻🇳", ".vn"),
    "Laos": ("🇱🇦", ".la"),
    "The Philippines": ("🇵🇭", ".ph"),
    "Sri Lanka": ("🇱🇰", ".lk"),
    "Bangladesh": ("🇧🇩", ".bd"),
    "Nepal": ("🇳🇵", ".np"),
    "India": ("🇮🇳", ".in"),
    "Pakistan": ("🇵🇰", ".pk"),
    "Singapore": ("🇸🇬", ".sg"),
    "Turkey": ("🇹🇷", ".tr"),
    "Brazil": ("🇧🇷", ".br"),
    "How to Identify the Regions of Brazil": ("🇧🇷", ".br"),
    "Paraguay": ("🇵🇾", ".py"),
    "Argentina": ("🇦🇷", ".ar"),
    "Uruguay": ("🇺🇾", ".uy"),
    "Ecuador": ("🇪🇨", ".ec"),
    "Colombia": ("🇨🇴", ".co"),
    "Peru": ("🇵🇪", ".pe"),
    "Bolivia": ("🇧🇴", ".bo"),
    "Chile": ("🇨🇱", ".cl"),
    "Curaao": ("🇨🇼", ".cw"),
    "Curaçao": ("🇨🇼", ".cw"),
}

# Left Driving Countries according to official guide
LEFT_DRIVING = {
    "The U.K.", "Ireland", "The Isle of Man", "Jersey", "Malta", "Cyprus",
    "South Africa", "Botswana", "Eswatini", "Lesotho", "Namibia", "Kenya", "Uganda",
    "Japan", "Hong Kong", "Macau", "Singapore", "Malaysia", "Thailand", "Indonesia",
    "Sri Lanka", "Bangladesh", "India", "Bhutan", "Pakistan",
    "Australia", "New Zealand", "Christmas Island",
    "US Virgin Islands", "Bermuda"
}

def get_driving_side(country_name):
    if country_name in LEFT_DRIVING:
        return "Left"
    return "Right"

print("Setup maps complete.")
